### ISSUE TITLE
Double execution

### ISSUE THREAD

**Issue by derBroBro** [alestic/alestic-unreliable-town-clock#2]
Hello,

first of all thank you very much for the great idea. 
Saddly it looks like the topic is currently executed two times with an offset of 2 minutes.

Do you've any idea how it comes to that behavior?

Malte

**Comment by ehammond** [comment]
Malte: Thanks for reaching out. CloudWatch Metrics is showing a consistent 4 messages an hour being published to the SNS topic. Logs and other subscribers are showing one invocation per message at 4 an hour as well.

There are a few things that might be going on here. Is there any chance you have two different Lambda functions subscribed to the SNS Topic performing the same task?

I believe SNS will retry sending a message to an AWS Lambda function if it fails. Is there a chance that your function is not executing successfully?

I could look into further details in the SNS topic delivery attempt logs if you send me
- ARN of the Lambda function(s) you have subscribed to the SNS Topic.
- Sample timestamps where you received duplicates.
- Complete copy of the two SNS messages that were received (if possible)

If you don't want to post it publicly here, send me an email (first name at my site domain).

**Comment by derBroBro** [comment]
Hi Eric,

thank you for your detauled responce. I will check first the "unique_id". 
The function finished without a "done" but should still successfull. 

Intressting could be that I substribed to the topics in us-east-1 but the function is located in eu-west-1 - it works but I'am not sure if this can be also a problem.

Malte

**Comment by derBroBro** [comment]
Ok looks like I realy get three messages, each with the same unique_id. 

Checking an example SNS topics, I saw the (HTTP) "numRetries" option which is per default also at three retries. 

Do you think this could be the issue?

Malte

**Comment by ehammond** [comment]
Malte: SNS does retry the message delivery (AWS Lambda function invocation) if your function does not complete successfully. You may want to use the AWS Forums for help in figuring out how to indicate a successful invocation to the caller.

It appears that what is going on here is normal AWS functionality and not an issue with the Unreliable Town Clock, so I am closing this issue.

If you would like me to investigate further, please provide the above requested information.
